name: terraform-apply

on:
  push:
    branches: [dev, staging, main]
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest

    # Current branch decides environment (dev/staging/main->prod)
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

    strategy:
      fail-fast: false
      matrix:
        stack: [networking, platform]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform init
        working-directory: infra/environments/${{ github.ref_name == 'main' && 'prod' || github.ref_name }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: infra/environments/${{ github.ref_name == 'main' && 'prod' || github.ref_name }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        env:
          TF_VAR_project: terraform_gitops
          TF_VAR_environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
          TF_VAR_region: ${{ vars.AWS_REGION }}
        run: terraform apply -input=false -auto-approve
