name: terraform-plan

on:
  pull_request:
    branches: [dev, staging, main]
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest

    # PR base branch decides environment (dev/staging/main->prod)
    environment: ${{ github.base_ref == 'main' && 'prod' || github.base_ref }}

    strategy:
      fail-fast: false
      matrix:
        env: [dev, staging, prod]
        stack: [networking, platform]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.role.outputs.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform fmt (check)
        working-directory: infra/environments/${{ github.base_ref == 'main' && 'prod' || github.base_ref }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: infra/environments/${{ github.base_ref == 'main' && 'prod' || github.base_ref }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: infra/environments/${{ github.base_ref == 'main' && 'prod' || github.base_ref }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform validate

      - name: Terraform plan
        working-directory: infra/environments/${{ github.base_ref == 'main' && 'prod' || github.base_ref }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        env:
          TF_VAR_project: terraform_gitops
          TF_VAR_environment: ${{ github.base_ref == 'main' && 'prod' || github.base_ref }}
          TF_VAR_region: ${{ vars.AWS_REGION }}
        run: terraform plan -input=false -no-color
