name: terraform-plan

on:
  pull_request:
    branches: [dev, staging, main]
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    environment: ${{ matrix.env }}
    strategy:
      fail-fast: false
      matrix:
        env: [dev, staging, prod]
        stack: [networking, platform]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env role
        id: role
        run: |
          if [ "${{ matrix.env }}" = "dev" ]; then
            echo "ROLE_ARN=arn:aws:iam::<ACCOUNT_ID>:role/gitops-terraform-dev" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.env }}" = "staging" ]; then
            echo "ROLE_ARN=arn:aws:iam::<ACCOUNT_ID>:role/gitops-terraform-staging" >> $GITHUB_OUTPUT
          else
            echo "ROLE_ARN=arn:aws:iam::<ACCOUNT_ID>:role/gitops-terraform-prod" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
           role-to-assume: ${{ vars.AWS_ROLE_ARN }}
           aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform fmt (check)
        working-directory: infra/environments/${{ matrix.env }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: infra/environments/${{ matrix.env }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: infra/environments/${{ matrix.env }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform validate

      - name: Terraform plan
        working-directory: infra/environments/${{ matrix.env }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform plan -input=false -no-color
