name: terraform-apply

on:
  push:
    branches: [dev, staging, main]
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: [networking, platform]

    # Map git branch -> environment name
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment name
        id: env
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Set role ARN
        id: role
        run: |
          if [ "${{ steps.env.outputs.ENV }}" = "dev" ]; then
            echo "ROLE_ARN=arn:aws:iam::<ACCOUNT_ID>:role/gitops-terraform-dev" >> $GITHUB_OUTPUT
          elif [ "${{ steps.env.outputs.ENV }}" = "staging" ]; then
            echo "ROLE_ARN=arn:aws:iam::<ACCOUNT_ID>:role/gitops-terraform-staging" >> $GITHUB_OUTPUT
          else
            echo "ROLE_ARN=arn:aws:iam::<ACCOUNT_ID>:role/gitops-terraform-prod" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform init
        working-directory: infra/environments/${{ steps.env.outputs.ENV }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: infra/environments/${{ steps.env.outputs.ENV }}/${{ vars.AWS_REGION }}/${{ matrix.stack }}
        run: terraform apply -input=false -auto-approve
